### ISSUE TITLE
TimeMachine and zfs tools

### ISSUE THREAD

**Issue by spamwax** [WoLpH/zfs-utils-osx#2]
Hi

Can I use this to create zpools and mount them to be used as a TimeMachine drive?

**Comment by wolph** [comment]
Yes indeed, after creating and mounting the zpool it should be available within TimeMachine

**Comment by spamwax** [comment]
can you briefly explain how it works please? does it create virtual devices that need to be formatted as HFS+? The reason I am asking is because it seems TimeMachine can only work on HFS+ unless some sort of sparsebundle (?!) file is created on zfs.

**Comment by wolph** [comment]
ZFS is a filesystem of it's own similar to HFS+ but generally much more reliable and has quite a few more features.

What this script does is it creates a virtual ZFS pool with multiple disks so you can (hopefully) reach a bit more reliability than HFS+ has by default. Unfortunately Apple never made the switch to ZFS even though they have been hinting for years that they would. Initially many people assumed that the TimeMachine would have been build using ZFS... unfortunately the TimeMachine is just a bunch of hacks on top of each other using hidden directories with hard links.

Thinking about it, with reliability in mind I wouldn't recommend using TimeMachine on top of a ZFS drive but instead use the ZFS snapshot feature for backups. TimeMachine is really not all that reliable anyhow so I wouldn't recommend using it as a primary backup solution.

With ZFS you can create snapshots which completely freeze the state of a disk at that point in time. You can create as many as you want so to backup your files you could simply make regular snapshots (only the difference between snapshots takes space). For extra reliability you can use the ZFS send command to copy the filesystem to a remote device if needed.

**Comment by spamwax** [comment]
thanks for the explanation. My main reason to use TimeMachine as a backup is to be able to painlessly restore my computer to a new Mac machine in case of new purchase or system failure.
For my 'data', I am planning to backup HFS content into a mirrored zfs pool.

**Comment by wolph** [comment]
In that case this method is completely unsuitable since osx has no native
zfs support. Personally I'd recommend carbon copy cloner, you can even boot
straight from those backups so if you back it up to an external drive you
can boot from it.
